KS-1-1 create hello world
art-cherepan/KotlinSprint pull request #1
Opened 2024-08-14 00:16 UTC by art-cherepan

2024-08-15 18:23 UTC, ievetrovdev requested changes

2024-08-15 18:23 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    println("Hello world")
Привет. Напомню условие первого задания вкратце:  **Пишем логику экрана приложения для интернет-магазина. Представим, что у интернет-магазина было 75 заказов. Нужно продумать релевантные названия и корректно объявить 2 переменные, которые будут содержать:**
**- количество заказов,**
**- текст с благодарностью за покупку (текст на твое усмотрение).**
**Задай “говорящие” наименования переменных (например, для сторон прямоугольника не a и b, а height и width). Названия переменных должны состоять из нескольких слов. Тип переменных указывать принудительно.**

2024-08-16 00:03 UTC, art-cherepan commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    println("Hello world")
Сори, это было задание для 0 урока (нужно было переименовать ветку, да)

Добавил переменные из  задания

P.S. возможно, в боте есть косячок: когда кликаешь в разделе задач на "0: Старт спринта", далее кликаешь на "4. Практика GIT", затем "Отправить решение", то пишет, что Отправьте решение задачи 4 к уроку 1

2024-08-16 00:04 UTC, art-cherepan commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    println("Hello world")
![Uploading Снимок экрана 2024-08-16 в 07.03.16.png…]()

2024-08-16 00:04 UTC, art-cherepan commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    println("Hello world")
<img width="661" alt="Снимок экрана 2024-08-16 в 07 03 16" src="https://github.com/user-attachments/assets/5f908390-5f6f-464e-893b-2d857a473302">

2024-08-16 10:30 UTC, ievetrovdev approved these changes

2024-08-19 00:09 UTC, merged