KS-2-5 Вывести итоговую сумму по депозиту
art-cherepan/KotlinSprint pull request #10
Opened 2024-08-19 00:00 UTC by art-cherepan

2024-08-19 21:14 UTC, ievetrovdev requested changes

2024-08-19 21:14 UTC, ievetrovdev commented on src/main/kotlin/lesson2/task5.kt
> +    println("Итоговая сумма: %.3f".format(totalAmount)) //почему-то результат выводит через заяптую, а не через точку (дробная часть)
Такие комментарии следует  оставлять в  самом ПР на гитхаб, а не в коде. Точка или запятая  меняются  в  зависимости  от локали по умолчанию, но для данной задачи не имеет значения

2024-08-20 07:23 UTC, art-cherepan commented on src/main/kotlin/lesson2/task5.kt
> +    println("Итоговая сумма: %.3f".format(totalAmount)) //почему-то результат выводит через заяптую, а не через точку (дробная часть)
Ок, учту на будущее

2024-08-20 20:14 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-08-22 14:55 UTC, merged