KS-21-2 Добавить функцию-расширение для подсчета четных чисел в списке
art-cherepan/KotlinSprint pull request #103
Opened 2024-12-15 01:27 UTC by art-cherepan

2024-12-15 13:43 UTC, ievetrovdev requested changes

2024-12-15 13:43 UTC, ievetrovdev commented on src/main/kotlin/lesson21/task2/Main.kt
> +    for (number in this) {
Предлагаю уже максимально использовать инструменты языка и для поиска суммы использовать соответствующие экстеншены: для фильтрации и нахождения суммы.

2024-12-17 00:27 UTC, art-cherepan commented on src/main/kotlin/lesson21/task2/Main.kt
> +    for (number in this) {
Переделал через методы filter и sum

2024-12-17 06:56 UTC, ievetrovdev approved these changes

2024-12-17 16:40 UTC, merged