KS-21-4 Добавить функцию расширение класса File
art-cherepan/KotlinSprint pull request #105
Opened 2024-12-17 16:22 UTC by art-cherepan

2024-12-18 06:46 UTC, ievetrovdev requested changes

2024-12-18 06:46 UTC, ievetrovdev commented on src/main/kotlin/lesson21/task4/Main.kt
> +fun File.customWrite(text: String, path: String) {
Передать путь до файла не нужно, ты уже и так работаешь с конкретным файлом, обратиться можно через this

2024-12-22 08:09 UTC, art-cherepan commented on src/main/kotlin/lesson21/task4/Main.kt
> +fun File.customWrite(text: String, path: String) {
Убрал путь до файла из аргументов

2024-12-22 12:59 UTC, ievetrovdev approved these changes

2024-12-22 15:34 UTC, merged