KS-22-4 Добавить класс MainScreenViewModel
art-cherepan/KotlinSprint pull request #110
Opened 2024-12-22 09:19 UTC by art-cherepan

2024-12-22 19:52 UTC, ievetrovdev requested changes

2024-12-22 19:52 UTC, ievetrovdev commented on src/main/kotlin/lesson22/task4/Main.kt
> +    val isLoading: Boolean = false,
Давай все обернем в общий класс MainScreenViewModel(). И внутри ВМ будет встроенный дата класс для хранения стейта

2024-12-23 05:07 UTC, art-cherepan commented on src/main/kotlin/lesson22/task4/Main.kt
> +    val isLoading: Boolean = false,
Перенес `MainScreenState` во VM

2024-12-23 20:21 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-12-26 01:21 UTC, merged