KS-22-5 Использовать компонентные функции
art-cherepan/KotlinSprint pull request #111
Opened 2024-12-22 16:38 UTC by art-cherepan

2024-12-22 19:53 UTC, ievetrovdev requested changes

2024-12-22 19:53 UTC, ievetrovdev commented on src/main/kotlin/lesson22/task5/Main.kt
> +    val (placeOrEventName, placeOrEventDescription, eventDateTime, distanceToEarth) = alphaCentauri
в задании было сказано про компонентные функции (component1, component2...)

2024-12-23 05:12 UTC, art-cherepan commented on src/main/kotlin/lesson22/task5/Main.kt
> +    val (placeOrEventName, placeOrEventDescription, eventDateTime, distanceToEarth) = alphaCentauri
Переделал на компонентные функции

2024-12-23 20:21 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-12-26 01:22 UTC, merged