KS-3-5 Распарсить ответ сервера
art-cherepan/KotlinSprint pull request #15
Opened 2024-08-20 07:39 UTC by art-cherepan

2024-08-20 13:50 UTC, ievetrovdev requested changes

2024-08-20 13:50 UTC, ievetrovdev commented on src/main/kotlin/lesson3/task5.kt
> +    val logStrToList = logStr.split(";")
Мы пользуемся сплит и обрати внимание на его сигнатуру. метод имеет ключевое слово vararg - то есть он может принимать произвольное количество параметров. то есть в данном случае разделителей. Подробнее тут https://metanit.com/kotlin/tutorial/3.2.php

2024-08-22 15:14 UTC, art-cherepan commented on src/main/kotlin/lesson3/task5.kt
> +    val logStrToList = logStr.split(";")
Добавил несколько разделителдей

2024-08-23 07:07 UTC, ievetrovdev approved these changes

2024-08-23 08:52 UTC, merged