KS-5-4 Добавить функцию верификации пользователя
art-cherepan/KotlinSprint pull request #19
Opened 2024-08-24 08:39 UTC by art-cherepan

2024-08-24 19:35 UTC, ievetrovdev requested changes

2024-08-24 19:35 UTC, ievetrovdev commented on src/main/kotlin/lesson5/task4.kt
Необходимо вывести те варианты текстовых сообщений, что  указаны в задании

2024-09-08 14:30 UTC, art-cherepan commented on src/main/kotlin/lesson5/task4.kt
Лишние учетки удалил

2024-09-08 21:36 UTC, ievetrovdev approved these changes
Все верно, молодец!

2024-09-08 23:35 UTC, merged