KS-5-5 Добавить улучшенную лотерею
art-cherepan/KotlinSprint pull request #20
Opened 2024-08-24 09:04 UTC by art-cherepan

2024-08-24 19:36 UTC, ievetrovdev requested changes

2024-08-24 19:36 UTC, ievetrovdev commented on src/main/kotlin/lesson5/task5.kt
> +        Random.nextInt(RANDOM_LOTTERY_VALUE_FROM, RANDOM_LOTTERY_VALUE_UNTIL)
Любой импорт – лишний код в классе. Неиспользуемый импорт – неиспользуемый код. Существуют условно тонкие материи, когда надо использовать какую-то конкретную реализацию под капотом. Поэтому обоснованно может быть вызвать некую альтернативу из Котлин или похожий функционал, но с другим внутренним алгоритмом из Джавы. Ситуативно. Здесь я бы использовал экстеншн получения рандомного числа из диапазона: (RANDOM_LOTTERY_VALUE_FROM..RANDOM_LOTTERY_VALUE_UNTIL).random()

2024-09-08 12:04 UTC, art-cherepan commented on src/main/kotlin/lesson5/task5.kt
> +        Random.nextInt(RANDOM_LOTTERY_VALUE_FROM, RANDOM_LOTTERY_VALUE_UNTIL)
Заменил на .random()

2024-09-08 21:35 UTC, ievetrovdev approved these changes
Все верно, молодец!

2024-09-08 23:34 UTC, merged