KS-4-3 Определить благоприятные условия
art-cherepan/KotlinSprint pull request #23
Opened 2024-08-24 09:56 UTC by art-cherepan

2024-09-03 14:21 UTC, ievetrovdev requested changes

2024-09-03 14:21 UTC, ievetrovdev commented on src/main/kotlin/lesson4/task3.kt
> +            && favorableTimesOfYear.contains(timeOfYear)
хоть и согласно https://kotlinlang.org/docs/coding-conventions.html конвенции нет строгих правил переноса длинных условия, на моей практике я везде встречал так: сначала на строке остается && / || , а затем строка переносится

2024-09-03 14:21 UTC, ievetrovdev commented on src/main/kotlin/lesson4/task3.kt
> +            && isOpenAwning
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не лучшая практика. Предлагаю добавить переменные) Согласно условию следует проинициализировать значения с которыми сравниваются критерии) их, кстати, стоит вынести в константы, так как они постоянные и не планируются изменяться после компиляции.

2024-09-03 14:21 UTC, ievetrovdev commented on src/main/kotlin/lesson4/task3.kt
> +): Boolean {
Хоть это не ошибка, но это базовые задания и использование функции излишне

2024-09-08 10:24 UTC, art-cherepan commented on src/main/kotlin/lesson4/task3.kt
> +            && favorableTimesOfYear.contains(timeOfYear)
Оставил && на строке выше

2024-09-08 10:25 UTC, art-cherepan commented on src/main/kotlin/lesson4/task3.kt
> +            && isOpenAwning
Вынес в константы

2024-09-08 10:25 UTC, art-cherepan commented on src/main/kotlin/lesson4/task3.kt
> +): Boolean {
Убрал функцию, все сделал в основной пограмме

2024-09-08 11:42 UTC, ievetrovdev approved these changes

2024-09-08 11:45 UTC, merged