KS-4-4 Вывести программу тренировок для определенного дня
art-cherepan/KotlinSprint pull request #24
Opened 2024-08-24 10:29 UTC by art-cherepan

2024-09-03 14:23 UTC, ievetrovdev requested changes

2024-09-03 14:23 UTC, ievetrovdev commented on src/main/kotlin/lesson4/task4.kt
> +fun getProgramOfTraining(numberOfTrainingDay: Int): Map<String, Boolean> {
Тут случай когда усложнение ради усложнения) мне кажется пока не стоит прям злоупотреблять функциями, потому что чувствую, что не до конца понимаешь принцип их применения) на эту тему еще будут задания, плавно подводящие к целесообразности использования)

Сделай все как можно проще только в main, хватит 2 переменных

2024-09-08 10:26 UTC, art-cherepan commented on src/main/kotlin/lesson4/task4.kt
> +fun getProgramOfTraining(numberOfTrainingDay: Int): Map<String, Boolean> {
Убрал функцию, все сделал в основной программе

2024-09-08 11:42 UTC, ievetrovdev approved these changes

2024-09-08 11:45 UTC, merged