KS-7-5 Сгенерировать усиленный пароль
art-cherepan/KotlinSprint pull request #35
Opened 2024-09-12 15:59 UTC by art-cherepan

2024-09-12 20:37 UTC, ievetrovdev requested changes

2024-09-12 20:37 UTC, ievetrovdev commented on src/main/kotlin/lesson7/task5.kt
> +                else -> password += ('A'..'Z').random()
Давай упростим. Символьные диапазоны можно складывать вместе для получения одного общего набора символов. Например, вот так val allChars = ('a'..'z') + ('A'..'Z') + ('0'..'9')

2024-09-12 23:45 UTC, art-cherepan commented on src/main/kotlin/lesson7/task5.kt
> +                else -> password += ('A'..'Z').random()
Ага, точно. Упростил

2024-09-13 20:24 UTC, ievetrovdev approved these changes
Все верно, отлично что есть проверка на пароль после генерации!

2024-09-14 14:47 UTC, merged