KS-8-1 Вывecти количество просмтров за неделю
art-cherepan/KotlinSprint pull request #36
Opened 2024-09-13 00:19 UTC by art-cherepan

2024-09-13 20:26 UTC, ievetrovdev requested changes

2024-09-13 20:26 UTC, ievetrovdev commented on src/main/kotlin/lesson8/task1.kt
> +    }
Можно без цикла, воспользуйся .sum()

2024-09-14 14:50 UTC, art-cherepan commented on src/main/kotlin/lesson8/task1.kt
> +    }
Спасибо, упростил

2024-09-14 19:19 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-09-17 00:00 UTC, merged