KS-1-4 Добавить переменные и их типы
art-cherepan/KotlinSprint pull request #4
Opened 2024-08-16 09:16 UTC by art-cherepan

2024-08-16 10:29 UTC, ievetrovdev requested changes

2024-08-16 10:29 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task4.kt
> +    val partOfDay: Float = 0.075.toFloat()
Метод `toFloat()` преобразует значение типа `Double` в `Float`. Тут что-то другое нужно указать после 0.075.
Всё правильно, переменная типа Float, но как мы присваиваем значения для переменных с данным типов данных?

2024-08-17 14:49 UTC, art-cherepan commented on src/main/kotlin/lesson1/lesson1_task4.kt
> +    val partOfDay: Float = 0.075.toFloat()
Исправил

2024-08-17 15:14 UTC, ievetrovdev approved these changes

2024-08-19 00:10 UTC, merged