KS-9-2 Добавить ингредиенты в список
art-cherepan/KotlinSprint pull request #42
Opened 2024-09-19 08:56 UTC by art-cherepan

2024-09-19 15:19 UTC, ievetrovdev requested changes

2024-09-19 15:19 UTC, ievetrovdev commented on src/main/kotlin/lesson9/task2.kt
> +    } while (userChoose != "нет")
Согласно условию: `для обработки ответа пользователя используй метод сравнения строк с игнорированием регистра: equals`
Давай поправим)

2024-09-19 15:19 UTC, ievetrovdev commented on src/main/kotlin/lesson9/task2.kt
> +        if (userChoose == "да") {
Можно запрашивать строку прям в условии. Тут не обязательна дополнительная переменная в силу того, что используем ее только один раз.

2024-09-20 08:24 UTC, art-cherepan commented on src/main/kotlin/lesson9/task2.kt
> +    } while (userChoose != "нет")
Перечитал еще раз условие задачи KS-9-2, но не увидел там ничего про `equals`

Добавил проверку строк через `equals`

2024-09-20 08:26 UTC, art-cherepan commented on src/main/kotlin/lesson9/task2.kt
> +        if (userChoose == "да") {
Не совсем понял. Переменная `userChoose ` используется для проверки на ввод `да` от пользователя, а также для условия выхода из цикла (ввод `нет`)

2024-09-20 19:02 UTC, ievetrovdev approved these changes

2024-09-21 15:00 UTC, merged