KS-2-1 Вывести среднее арифметическое
art-cherepan/KotlinSprint pull request #6
Opened 2024-08-17 15:22 UTC by art-cherepan

2024-08-17 21:38 UTC, ievetrovdev requested changes

2024-08-17 21:38 UTC, ievetrovdev commented on src/main/kotlin/lesson2/task1.kt
> +    val arithmeticMean = (firstStudentPoint + secondStudentPoint + thirdStudentPoint + fourthStudentPoint) / 4
Все окей, но чтобы снизить риск ошибок, предлагаю еще вынести 4 в переменную. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-08-18 14:41 UTC, art-cherepan commented on src/main/kotlin/lesson2/task1.kt
> +    val arithmeticMean = (firstStudentPoint + secondStudentPoint + thirdStudentPoint + fourthStudentPoint) / 4
Перенес 4 в константу

2024-08-19 14:38 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-08-19 14:40 UTC, merged