KS-14-5 Добавить класс чата и распечатать все сообщения
art-cherepan/KotlinSprint pull request #71
Opened 2024-10-27 12:06 UTC by art-cherepan

2024-10-27 21:42 UTC, ievetrovdev requested changes

2024-10-27 21:42 UTC, ievetrovdev commented on src/main/kotlin/lesson14/task5/Main.kt
> +) {
Стоит добавить поле, которое бы хранило последний добавленный id. Так можно будет легко назначать новые id для сообщений, увеличивая его +1

2024-10-28 06:53 UTC, art-cherepan commented on src/main/kotlin/lesson14/task5/Main.kt
> +) {
Добавил поле для хранения айдишников в классе чата.

2024-10-28 20:46 UTC, ievetrovdev approved these changes
Отлично, все верно!

2024-10-29 14:05 UTC, merged