KS-15-4 Добавить классы и интерфейс для магазина музыкальных инструментов
art-cherepan/KotlinSprint pull request #75
Opened 2024-11-06 16:32 UTC by art-cherepan

2024-11-06 19:45 UTC, ievetrovdev requested changes

2024-11-06 19:45 UTC, ievetrovdev commented on src/main/kotlin/lesson15/task4/Main.kt
> +    }
Реализация должны быть в классе, а не в интерфейсе

2024-11-06 23:57 UTC, art-cherepan commented on src/main/kotlin/lesson15/task4/Main.kt
> +    }
Перенес в класс

2024-11-07 15:18 UTC, art-cherepan commented on src/main/kotlin/lesson15/task4/Main.kt
> +    }
Кстати, а в каких случаях можно добавлять реализацию в интерфейс ?

2024-11-07 22:42 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-11-07 23:56 UTC, merged