KS-15-5 Реализовать классы транспортных средств
art-cherepan/KotlinSprint pull request #76
Opened 2024-11-07 16:37 UTC by art-cherepan

2024-11-07 22:56 UTC, ievetrovdev requested changes

2024-11-07 22:56 UTC, ievetrovdev commented on src/main/kotlin/lesson15/task5/Main.kt
> +interface PassengersTransportation {
Это не интерфейс, а скорее абстрактный класс. Интерфейс не должен быть привязан к "объекту", а к привязан к свойству объекта, как выше Movable - то есть движимое. Это требование, что бы любой движущийся объект имел такие то методы. А PassengersTransportation  это абстракция, но уже не интерфейс

2024-11-08 00:41 UTC, art-cherepan commented on src/main/kotlin/lesson15/task5/Main.kt
> +interface PassengersTransportation {
Переделал логику

2024-11-08 22:03 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-11-12 14:55 UTC, merged