KS-16-2 Добавить класс окружности
art-cherepan/KotlinSprint pull request #78
Opened 2024-11-12 16:01 UTC by art-cherepan

2024-11-12 19:07 UTC, ievetrovdev requested changes

2024-11-12 19:07 UTC, ievetrovdev commented on src/main/kotlin/lesson16/task2/Main.kt
> +    val PI: Double = 3.14
Нужно сделать его приватной константной, но не в классе, а в файле

2024-11-15 09:22 UTC, art-cherepan commented on src/main/kotlin/lesson16/task2/Main.kt
> +    val PI: Double = 3.14
Вынес в приватную константу

2024-11-15 22:49 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-11-16 12:37 UTC, merged