KS-16-4 Добавить класс заказа интернет-магазина
art-cherepan/KotlinSprint pull request #80
Opened 2024-11-15 09:49 UTC by art-cherepan

2024-11-15 22:54 UTC, ievetrovdev requested changes

2024-11-15 22:54 UTC, ievetrovdev commented on src/main/kotlin/lesson16/task4/Main.kt
> +        orderStatus = _orderStatus
Согласно заданию: "Поменять статус заказа можно только отправив заявку менеджеру. Имитируй это действие отдельной **публичной функцией**✅. Она будет принимать новый статус и обращаться к **внутреннему методу класса для изменения статуса**❌."

- Внутренний метод не реализован, изменение происходит напрямую обращением к полю, что не по заданию

2024-11-16 12:43 UTC, art-cherepan commented on src/main/kotlin/lesson16/task4/Main.kt
> +        orderStatus = _orderStatus
Сделал метод приватным. Добавил публичный метод для получения нового статуса заказа

2024-11-16 23:50 UTC, ievetrovdev approved these changes
Все верно, молодец!

2024-11-17 04:53 UTC, merged