KS-16-5 Добавить класс игрока
art-cherepan/KotlinSprint pull request #81
Opened 2024-11-15 10:18 UTC by art-cherepan

2024-11-15 22:55 UTC, ievetrovdev requested changes

2024-11-15 22:55 UTC, ievetrovdev commented on src/main/kotlin/lesson16/task5/Main.kt
> +            occurrenceOfDeath()
Персонажа заставляют умереть при каждом получении урона. Надо бы вынести вызов этой функции в отдельное условие

2024-11-17 05:04 UTC, art-cherepan commented on src/main/kotlin/lesson16/task5/Main.kt
> +            occurrenceOfDeath()
Добавил проверку на то, жив игрок или нет

2024-11-17 22:41 UTC, ievetrovdev approved these changes
Отличное решение, все верно!

2024-11-18 06:41 UTC, merged