KS-17-3 Добавить класс Папки и деттеры для свойств
art-cherepan/KotlinSprint pull request #84
Opened 2024-11-19 16:14 UTC by art-cherepan

2024-11-19 22:57 UTC, ievetrovdev requested changes

2024-11-19 22:57 UTC, ievetrovdev commented on src/main/kotlin/lesson17/task3/Main.kt
> +                return "Секретно"
По заданию нужно возвращать строку “скрытая папка”

2024-11-22 09:31 UTC, art-cherepan commented on src/main/kotlin/lesson17/task3/Main.kt
> +                return "Секретно"
Изменил

2024-11-22 20:32 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-11-23 04:59 UTC, merged