KS-17-5 Добавить класс пользователя
art-cherepan/KotlinSprint pull request #86
Opened 2024-11-23 05:42 UTC by art-cherepan

2024-11-23 22:14 UTC, ievetrovdev requested changes

2024-11-23 22:14 UTC, ievetrovdev commented on src/main/kotlin/lesson17/task5/Main.kt
> +            val regex = ".".toRegex()
Можно проще: "*".repeat(field.length)

2024-11-25 14:30 UTC, art-cherepan commented on src/main/kotlin/lesson17/task5/Main.kt
> +            val regex = ".".toRegex()
Исправил

2024-11-25 20:53 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-11-30 15:11 UTC, merged