KS-18-2 Добавить иерархию классов игральной кости
art-cherepan/KotlinSprint pull request #88
Opened 2024-11-23 15:30 UTC by art-cherepan

2024-11-23 22:46 UTC, ievetrovdev requested changes

2024-11-23 22:46 UTC, ievetrovdev commented on src/main/kotlin/lesson18/task2/Main.kt
> +    }
Метод всегда одинаковый, его реализацию нужно вынести в класс Dice

2024-11-23 22:46 UTC, ievetrovdev commented on src/main/kotlin/lesson18/task2/Main.kt
> +    abstract fun diceRoll()
Добавь поле, которое будет хранить число кубика, использовать его как "магическое число" в методе не верно

2024-11-25 15:01 UTC, art-cherepan commented on src/main/kotlin/lesson18/task2/Main.kt
> +    }
Унес метод в Dice

2024-11-25 15:01 UTC, art-cherepan commented on src/main/kotlin/lesson18/task2/Main.kt
> +    abstract fun diceRoll()
Добавил поле для хранения кол-ва граней кубика

2024-11-25 20:54 UTC, ievetrovdev approved these changes
Отличное решение, молодец!

2024-11-30 15:12 UTC, merged