KS-2-4 Вывести бафф по каждой руде
art-cherepan/KotlinSprint pull request #9
Opened 2024-08-18 15:00 UTC by art-cherepan

2024-08-19 14:40 UTC, ievetrovdev requested changes

2024-08-19 14:40 UTC, ievetrovdev commented on src/main/kotlin/lesson2/task4.kt
> +    return (oreCount * 0.2).toInt()
Для возможности гибкой работы с кодом, следует инициализировать согласно ТЗ проценты целым числом 20. И уже потом производить вычисление процентов. Таким образом, если нужен будет другой процент, достаточно будет поменять значение в одном месте.

2024-08-19 14:40 UTC, ievetrovdev commented on src/main/kotlin/lesson2/task4.kt
> +    return (oreCount * 0.2).toInt()
Значение 0.2 в этом коде являются магическими числами. Не лучшая практика)

2024-08-19 14:49 UTC, art-cherepan commented on src/main/kotlin/lesson2/task4.kt
> +    return (oreCount * 0.2).toInt()
Перенес процент по бафу в аргумент функции

2024-08-19 14:49 UTC, art-cherepan commented on src/main/kotlin/lesson2/task4.kt
> +    return (oreCount * 0.2).toInt()
Исправил

2024-08-19 22:05 UTC, ievetrovdev requested changes

2024-08-19 22:05 UTC, ievetrovdev commented on src/main/kotlin/lesson2/task4.kt
> +    return (oreCount * buffPercent) / 100
Все окей, но чтобы снизить риск ошибок, предлагаю еще вынести 100 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-08-20 20:13 UTC, ievetrovdev requested changes

2024-08-20 20:13 UTC, ievetrovdev commented on src/main/kotlin/lesson2/task4.kt
> +const val buffMaxPercent = 100
Нейминг констант отличен от обычных переменных. В [документации по ссылке](https://developer.android.com/kotlin/style-guide#constant_names) есть более полное описание стайл гайда

2024-08-22 14:53 UTC, art-cherepan commented on src/main/kotlin/lesson2/task4.kt
> +    return (oreCount * buffPercent) / 100
Вынес в константу

2024-08-22 14:53 UTC, art-cherepan commented on src/main/kotlin/lesson2/task4.kt
> +const val buffMaxPercent = 100
Исправил стиль нейминга для константы

2024-08-22 22:34 UTC, ievetrovdev approved these changes
Все  отлично, прекрасное решение!

2024-08-23 08:52 UTC, merged