KS-18-4 Добавить классы коробок
art-cherepan/KotlinSprint pull request #90
Opened 2024-11-30 16:49 UTC by art-cherepan

2024-11-30 20:40 UTC, ievetrovdev requested changes

2024-11-30 20:40 UTC, ievetrovdev commented on src/main/kotlin/lesson18/task4/Main.kt
> +    override fun calculateSurfaceArea(): Double = length * width * height
Это объем, а не площадь поверхности коробки

2024-11-30 20:40 UTC, ievetrovdev commented on src/main/kotlin/lesson18/task4/Main.kt
> +    override fun calculateSurfaceArea(): Double = ribLength.pow(3.0)
Аналогично, не верный расчет

2024-12-01 00:21 UTC, art-cherepan commented on src/main/kotlin/lesson18/task4/Main.kt
> +    override fun calculateSurfaceArea(): Double = ribLength.pow(3.0)
Исправил

2024-12-01 00:21 UTC, art-cherepan commented on src/main/kotlin/lesson18/task4/Main.kt
> +    override fun calculateSurfaceArea(): Double = length * width * height
Исправил

2024-12-01 22:06 UTC, ievetrovdev approved these changes
Отличное решение, все верно!

2024-12-01 23:36 UTC, merged