KS-19-4 Добавить класс танка
art-cherepan/KotlinSprint pull request #95
Opened 2024-12-01 07:13 UTC by art-cherepan

2024-12-02 18:16 UTC, ievetrovdev requested changes

2024-12-02 18:16 UTC, ievetrovdev commented on src/main/kotlin/lesson19/task4/Main.kt
> +    private var cartridgeType: Cartridge? = null
Предлагаю перенести поле с зарядом в основной конструктор, чтобы была опция создания с каким-либо снарядом. Так код будет более гибким.

2024-12-03 08:55 UTC, art-cherepan commented on src/main/kotlin/lesson19/task4/Main.kt
> +    private var cartridgeType: Cartridge? = null
Перенес в основной конструктор

2024-12-03 16:41 UTC, ievetrovdev approved these changes

2024-12-12 16:01 UTC, merged